# Generated by Django 5.0.7 on 2024-10-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='upload',
            new_name='image',
        ),
    ]
